#pragma once

// ============================================================================
// Python template for D-Wave quantum annealing submission.
//
// Placeholders (replaced by C++ at runtime):
//   __INPUT_PATH__         Path to encoded .json model
//   __OUTPUT_PATH__        Path for results .json output
//   __SOLVER_NAME__        D-Wave solver name
//   __ANNEALING_TIME__     Annealing time in microseconds
//   __NUM_READS__          Number of reads (shots)
//   __USE_INHOMOGENEOUS__  Python bool: True or False
//   __ANNEAL_OFFSETS__     Python dict: {qubit_idx: offset, ...}
// ============================================================================

inline const char* DWAVE_SUBMIT_TEMPLATE = R"PYTEMPLATE(#!/usr/bin/env python3
"""D-Wave quantum annealing submission script.
Auto-generated by solve_qa. Do not edit manually.
"""
import json
import time
import sys

try:
    from dwave.system import DWaveSampler
    from dwave.embedding import embed_bqm, unembed_sampleset
    from dwave.embedding.chain_strength import uniform_torque_compensation
    import dimod
    import minorminer
except ImportError as e:
    print(f"Error: Missing D-Wave Ocean SDK dependency: {e}", file=sys.stderr)
    print("Install with: pip install dwave-ocean-sdk", file=sys.stderr)
    sys.exit(1)


def main():
    # === Parameters (filled in by solve_qa) ===
    input_path        = "__INPUT_PATH__"
    output_path       = "__OUTPUT_PATH__"
    solver_name       = "__SOLVER_NAME__"
    annealing_time_us = __ANNEALING_TIME__
    num_reads         = __NUM_READS__
    use_inhomogeneous = __USE_INHOMOGENEOUS__
    anneal_offsets    = __ANNEAL_OFFSETS__

    # === Load encoded model ===
    with open(input_path) as f:
        model = json.load(f)

    # === Build BQM from terms ===
    linear = {}
    quadratic = {}
    offset = model.get("offset", 0.0)

    for key, coeff in model["terms"].items():
        indices = [int(x) for x in key.split(",")]
        if len(indices) == 1:
            linear[indices[0]] = linear.get(indices[0], 0.0) + coeff
        elif len(indices) == 2:
            pair = (indices[0], indices[1])
            quadratic[pair] = quadratic.get(pair, 0.0) + coeff
        else:
            print(f"Error: term '{key}' has degree {len(indices)} > 2. "
                  "Only QUBO/Ising models are supported.", file=sys.stderr)
            sys.exit(1)

    vartype = dimod.SPIN if model["variable_type"] == "SPIN" else dimod.BINARY
    bqm = dimod.BinaryQuadraticModel(linear, quadratic, offset, vartype)

    print(f"BQM: {len(bqm.variables)} variables, "
          f"{len(bqm.quadratic)} interactions, "
          f"vartype={bqm.vartype.name}", file=sys.stderr)

    # === Connect to D-Wave solver ===
    try:
        sampler = DWaveSampler(solver=solver_name)
    except Exception as e:
        print(f"Error connecting to D-Wave solver '{solver_name}': {e}",
              file=sys.stderr)
        sys.exit(1)

    print(f"Connected to {sampler.solver.name}", file=sys.stderr)

    # === Find embedding ===
    t_embed = time.time()

    # Use edgelists for find_embedding (adjacency dicts cause
    # 'int not iterable' in some minorminer/Ocean SDK versions).
    source_edgelist = list(bqm.quadratic.keys())
    target_edgelist = sampler.edgelist

    embedding = minorminer.find_embedding(source_edgelist, target_edgelist)
    if not embedding:
        print("Error: Could not find embedding for this problem on the "
              "selected solver.", file=sys.stderr)
        sys.exit(1)

    # Isolated variables (only linear terms, no quadratic) are not in
    # the source edgelist, so minorminer skips them.  Assign each to
    # an unused physical qubit so unembed_sampleset doesn't KeyError.
    used_physical = set()
    for chain in embedding.values():
        used_physical.update(chain)
    for v in bqm.variables:
        if v not in embedding:
            for pq in sampler.nodelist:
                if pq not in used_physical:
                    embedding[v] = [pq]
                    used_physical.add(pq)
                    print(f"  Isolated variable {v} -> physical qubit {pq}",
                          file=sys.stderr)
                    break
            else:
                print(f"Error: no free physical qubit for isolated variable {v}",
                      file=sys.stderr)
                sys.exit(1)

    embedding_time_s = time.time() - t_embed

    total_phys = sum(len(chain) for chain in embedding.values())
    max_chain  = max(len(chain) for chain in embedding.values())
    print(f"Embedding found in {embedding_time_s:.3f}s: "
          f"{total_phys} physical qubits, max chain length {max_chain}",
          file=sys.stderr)

    # Build target adjacency for embed_bqm (dict with set values)
    target_adj = {}
    for u, v in target_edgelist:
        target_adj.setdefault(u, set()).add(v)
        target_adj.setdefault(v, set()).add(u)
    for q in sampler.nodelist:
        target_adj.setdefault(q, set())

    # === Compute chain strength (uniform torque compensation) ===
    chain_strength = uniform_torque_compensation(bqm, embedding)

    # === Embed BQM ===
    embedded_bqm = embed_bqm(
        bqm, embedding, target_adj,
        chain_strength=chain_strength
    )

    # === Build submission parameters ===
    sample_kwargs = {
        "annealing_time": annealing_time_us,
        "num_reads":      num_reads,
        "answer_mode":    "histogram",
    }

    # === Map logical anneal offsets to physical qubits ===
    if use_inhomogeneous and anneal_offsets:
        num_physical   = sampler.properties["num_qubits"]
        phys_offsets   = [0.0] * num_physical
        offset_ranges  = sampler.properties.get("anneal_offset_ranges", None)

        for logical_q, chain in embedding.items():
            off = anneal_offsets.get(logical_q, 0.0)
            for physical_q in chain:
                val = off
                if offset_ranges and physical_q < len(offset_ranges):
                    lo, hi = offset_ranges[physical_q]
                    val = max(lo, min(hi, val))
                phys_offsets[physical_q] = val

        sample_kwargs["anneal_offsets"] = phys_offsets
        print(f"Inhomogeneous driving enabled (delta_max offsets mapped to "
              f"{total_phys} physical qubits)", file=sys.stderr)
    else:
        print("Uniform driving (no anneal offsets)", file=sys.stderr)

    # === Submit to D-Wave ===
    print(f"Submitting {num_reads} reads, annealing_time={annealing_time_us} us ...",
          file=sys.stderr)
    sampleset = sampler.sample(embedded_bqm, **sample_kwargs)

    # === Compute per-sample chain break counts (from embedded samples) ===
    chain_breaks_out = []
    for datum in sampleset.data(sorted_by=None):
        n_breaks = 0
        for logical_q, chain in embedding.items():
            if len(chain) > 1:
                first_val = datum.sample[chain[0]]
                for pq in chain[1:]:
                    if datum.sample[pq] != first_val:
                        n_breaks += 1
                        break
        chain_breaks_out.append({
            "breaks": n_breaks,
            "num_occurrences": int(datum.num_occurrences),
        })

    # === Unembed results ===
    unembedded = unembed_sampleset(sampleset, embedding, bqm)

    # === Extract timing information ===
    timing_info = sampleset.info.get("timing", {})

    # === Build output JSON ===
    num_total_qubits = (model["num_logical_qubits"]
                        + model["num_auxiliary_qubits"])
    default_val = 1 if vartype == dimod.SPIN else 0

    samples_out = []
    for datum in unembedded.data(sorted_by="energy"):
        values = [default_val] * num_total_qubits
        for var, val in datum.sample.items():
            idx = int(var)
            if 0 <= idx < num_total_qubits:
                values[idx] = int(val)
        samples_out.append({
            "values":          values,
            "energy":          float(datum.energy),
            "num_occurrences": int(datum.num_occurrences),
        })

    cs_val = (float(chain_strength)
              if isinstance(chain_strength, (int, float))
              else 0.0)

    # === Chain length list (one per logical variable) ===
    chain_lengths = [len(embedding[v]) for v in sorted(embedding.keys())]

    result = {
        "samples": samples_out,
        "timing": {
            "qpu_access_time":       timing_info.get("qpu_access_time", 0),
            "qpu_sampling_time":     timing_info.get("qpu_sampling_time", 0),
            "qpu_programming_time":  timing_info.get("qpu_programming_time", 0),
            "post_processing_time":  timing_info.get(
                "post_processing_overhead_time", 0),
        },
        "embedding_time_s":    embedding_time_s,
        "chain_strength":      cs_val,
        "num_physical_qubits": total_phys,
        "max_chain_length":    max_chain,
        "chain_lengths":       chain_lengths,
        "chain_breaks":        chain_breaks_out,
    }

    with open(output_path, "w") as f:
        json.dump(result, f)

    total_occ = sum(s["num_occurrences"] for s in samples_out)
    print(f"Done. {len(samples_out)} unique samples, "
          f"{total_occ} total occurrences.", file=sys.stderr)


if __name__ == "__main__":
    main()
)PYTEMPLATE";
